export enum Entities {
  ALL = "all",
  FLIGHT = "flight",
  FLIGHT_TYPE = "flightType",
  USER = "user",
  RIGHT = "right",
  ACTION = "action",
  ENTITY = "entity",
  PERMISSION = "permission",
  PROJECT = "project",
  PROJECT_TYPE = "projectType",
  ROLE = "role",
  CART = "cart",
  APPLICATION = "application",
  ANALYTIC = "analytic",
}
